# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:18-slim

# Install dependencies for puppeteer
RUN apt-get update && apt-get install -y \
    ca-certificates \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgtk-3-0 \
    libgbm1 \
    libpango-1.0-0 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libx11-6 \
    libxext6 \
    libxfixes3 \
    libxrender1 \
    libxcb1 \
    libnss3 \
    lsb-release \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY package.json package-lock.json tsconfig.json index.ts patient-info-topics.ts ./

# Install dependencies without running optional scripts
RUN npm install --ignore-scripts

# Build TypeScript if needed (tsx uses ts on the fly)
# Default command
CMD ["npx", "tsx", "index.ts"]
